---
title: "Microservices (k8s) - Tactical Plan"
config:
  flowchart:
    curve:basis
  theme: base
  themeVariables:
    primaryColor: '#eaf6f8'
    primaryTextColor: '#000000'
    primaryBorderColor: '#a3d5dc'
    lineColor: '#6fb8c9'
    edgeLabelBackground: 'transparent'
    fontFamily: 'arial'
    mainBkg: '#eaf6f8'
    secondBkg: '#d6ecf3'
    tertiaryColor: '#f0f9fb'
    clusterBkg: '#f5fbfc'
    clusterBorder: '#a3d5dc'
    background: '#ffffff'
    secondaryColor: '#d6ecf3'
    tertiaryTextColor: '#000000'
    secondaryTextColor: '#000000'
    textColor: '#000000'
    nodeTextColor: '#000000'
  themeCSS: '.edgeLabel, .edgeLabels, .edgeLabel *, .edgeLabels *, .edgeLabel .label, .edgeLabels .label, .edgeLabel p, .edgeLabels p, .edgeLabel div, .edgeLabels div, .edgeLabel foreignObject, .edgeLabels foreignObject, .edgeLabel rect, .edgeLabels rect, .edgeLabel span, .edgeLabels span, .label rect, tspan { background-color: transparent !important; background: transparent !important; fill: transparent !important; stroke: none !important; } .edgeLabel .label text, .edgeLabel text, .edgeLabels text, .edgeLabel p, .edgeLabels p, .edgeLabel span, .edgeLabels span { color: #4d4d4d !important; fill: #4d4d4d !important; }'
---

flowchart
  subgraph subMainContainer[" "]
    direction LR
    endUser@{ shape: sl-rect, label: "👤 End User" }
    internet@{ shape: cloud, label: "I  N  T  E  R  N  E  T" }
    firewall@{ shape: rect, label: "🧱 Firewall" }

    subgraph subDmz ["DMZ / Edge Cluster"]
      systemUser@{ shape: sl-rect, label: "👤 System User" }
      ldap@{ shape: bow-rect, label: "🪪 LDAP" }
      
      subgraph subApiGateway ["🌐 Ingress & API Gateway"]
          srvReactShell@{ shape: rect, label: "⚛️ React Shell" }
          srvAccessControl@{ shape: rect, label: "🛡 Access Control / AuthSidecar" }
      end
      extLoadBalancer@{ shape: rect, label: "External Load Balancer" }
      adminKubectl@{ shape: rect, label: "Admin (kubectl)" }
    end

    subgraph subNonDmz ["Kubernetes Cluster (Non DMZ)"]
      cloudProvider@{ shape: rect, label: "Cloud Provider" }

      subgraph subControlPlane ["Control Plane"]
          controllerManager@{ shape: rect, label: "Controller Manager" }
          scheduler@{ shape: rect, label: "Scheduler" }
          apiServer@{ shape: rect, label: "API Server" }
          etcdStorage@{ shape: h-cyl, label: "etcd" }
          cloudControllerManager@{ shape: rect, label: "Cloud Controller Manager" }

          controllerManager -.->|Handles Replicas, Endpoints, etc.| apiServer
          apiServer -.->|Sends controller requests| controllerManager
          scheduler -.->|Schedules Pods to Nodes| apiServer
          apiServer -.->|Sends scheduling requests| scheduler
          apiServer -->|Stores cluster state| etcdStorage
          cloudControllerManager -.->|Manages cloud-specific control logic| apiServer
          apiServer -.->|Sends cloud resource requests| cloudControllerManager
      end

      subgraph subMicroservices ["Microservices (1 Pod per Service)"]
        subgraph subWorkerNode1 ["Worker Node 1"]
            kubelet1@{ shape: rect, label: "Kubelet" }
            containerRuntime1@{ shape: rect, label: "Container Runtime" }
            ingressController@{ shape: rect, label: "🚦 Ingress Controller" }
            service1@{ shape: rect, label: "Service" }
            subgraph podA1 ["Pod (App A)"]
              subgraph containersA1["Container"]
                mfeService1@{ shape: curv-trap, label: "🧩 Microfrontend 1" }
                srvService1@{ shape: hex, label: "📦 Service 1 Container" }
                mfeService1 --- srvService1
              end
            end
            subgraph podB1 ["Pod (App B)"]
              subgraph containersB1["Container"]
                mfeService2@{ shape: curv-trap, label: "🧩 Microfrontend 2" }
                srvService2@{ shape: hex, label: "📦 Service 2 Container" }
                mfeService2 --- srvService2
              end
            end
            kubeProxy1@{ shape: rect, label: "Kube-Proxy" }

            kubelet1 -->|Manages| containerRuntime1
            ingressController edgeIngressToService@==>|Routes traffic to| service1
            edgeIngressToService@{ curve: linear, animate: true, animation: fast }
            service1 edgeService1A1@-.->|Forwards to| podA1
            edgeService1A1@{ curve: linear, animate: true, animation: fast }
            service1 edgeService1B1@-.->|Forwards to| podB1
            edgeService1B1@{ curve: linear, animate: true, animation: fast }
        end

        subgraph subWorkerNode2 ["Worker Node 2"]
            kubelet2@{ shape: rect, label: "Kubelet" }
            containerRuntime2@{ shape: rect, label: "Container Runtime" }
            subgraph podA2 ["Pod (App A)"]
              subgraph containersA2["Container"]
                mfeService3@{ shape: curv-trap, label: "🧩 Microfrontend 3" }
                srvService3@{ shape: hex, label: "📦 Service 3 Container" }
                mfeService3 --- srvService3
              end
            end
            subgraph podB2 ["Pod (App B)"]
              subgraph containersB2["Container"]
                mfeService4@{ shape: curv-trap, label: "🧩 Microfrontend 4" }
                srvService4@{ shape: hex, label: "📦 Service 4 Container" }
                mfeService4 --- srvService4
              end
            end
            kubeProxy2@{ shape: rect, label: "Kube-Proxy" }

            kubelet2 -->|Manages| containerRuntime2
        end

        subgraph subWorkerNode3 ["Worker Node 3"]
          kubelet3@{ shape: rect, label: "Kubelet" }
          containerRuntime3@{ shape: rect, label: "Container Runtime" }
          subgraph podNotification ["Notification Pod"]
            subgraph containersA3["Container"]
              srvNotification@{ shape: hex, label: "🔔 Notification Service" }
            end
          end
          eventsBus@{ shape: h-cyl, label: "📯 Message Broker / Event Mesh" }
          kubeProxy3@{ shape: rect, label: "Kube-Proxy" }
          kubelet3 -->|Manages| containerRuntime3
        end

        smsProvider@{ shape: rect, label: "📱 SMS Provider" }
        emailServer@{ shape: rect, label: "✉️ Email Server" }
        databaseStorage@{ shape: lin-cyl, label: "Database Server" }
        fileStorage@{ shape: lin-doc, label: "🗄️ File Storage" }   
      end

      subgraph subAudit ["Observability / Logging"]
          logElastic@{ shape: rect, label: "🔍 ElasticSearch" }
          logLogstash@{ shape: rect, label: "📥 FluentBit / Logstash" }
          logKibana@{ shape: rect, label: "📈 Kibana" }
      end

      adminUser@{ shape: sl-rect, label: "👤 Admin Console (Browser)" }
    end

    %% External Access Routing
    extLoadBalancer edgeIngressToReactShell@===>|Routes to| srvReactShell
    edgeIngressToReactShell@{ curve: linear, animate: true, animation: slow }
    extLoadBalancer edgeIngress@===>|Routes to| ingressController
    edgeIngress@{ curve: linear, animate: true, animation: slow }
    service1 edgeService1A2@-.->|Forwards to| podA2
    edgeService1A2@{ curve: linear, animate: true, animation: fast }

    service1 edgeService1B2@-.->|Forwards to| podB2
    edgeService1B2@{ curve: linear, animate: true, animation: fast }

    adminKubectl edgeAdminKubectl@==>|kubectl| apiServer
    edgeAdminKubectl@{ curve: linear, animate: true, animation: slow }

    %% Worker Node 1 Connections to Control Plane
    kubelet1 edgekubeletToApiServer@-.-|Reports status| apiServer
    edgekubeletToApiServer@{ curve: basis, animate: true, animation: fast }
    kubeProxy1 edgekubeProxy1ToApiServer@-.-|Applies| apiServer
    edgekubeProxy1ToApiServer@{ curve: basis, animate: true, animation: fast }

    %% Worker Node 2 Connections to Control Plane
    kubelet2 edgekubelet2ToApiServer@-.-|Reports status| apiServer
    edgekubelet2ToApiServer@{ curve: linear, animate: true, animation: fast }
    kubeProxy2 edgekubeProxy2@-.-|Applies| apiServer
    edgekubeProxy2@{ curve: linear, animate: true, animation: fast }

    %% Worker Node 3 Connections to Control Plane
    kubelet3 edgekubelet3ToApiServer@-.-|Reports status| apiServer
    edgekubelet3ToApiServer@{ curve: linear, animate: true, animation: fast }
    kubeProxy3 edgekubeProxy3@-.-|Applies| apiServer
    edgekubeProxy3@{ curve: linear, animate: true, animation: fast }

    %% External Cloud Provider Connections
    cloudProvider edgeCloudProvider@==>|Integration| cloudControllerManager
    edgeCloudProvider@{ curve: linear, animate: true, animation: fast }

    endUser edgeWeb@--- internet
    edgeWeb@{ curve: linear }

    internet edgeFirewall@==> |443| firewall
    edgeFirewall@{ curve: linear, animate: true, animation: slow }

    firewall edgeGateway@==> extLoadBalancer
    edgeGateway@{ curve: linear, animate: true, animation: slow }

    ldap edgeLdap@-.- srvAccessControl
    edgeLdap@{ curve: linear }

    systemUser edgeSysUser@-->|443| subApiGateway
    edgeSysUser@{ curve: linear }
    
    srvReactShell edgeMicro@==>|8080...| ingressController
    edgeMicro@{ curve: linear, animate: true, animation: fast }

    srvService4 edgeDb1@==> databaseStorage
    edgeDb1@{ curve: linear, animate: true, animation: fast }

    srvService3 edgeDb2@==> fileStorage
    edgeDb2@{ curve: linear, animate: true, animation: fast }

    subMicroservices edgeAudit@==>|5000| subAudit
    edgeAudit@{ curve: linear, animate: true, animation: fast }

    logLogstash edgeLog@--> |9200| logElastic
    edgeLog@{ curve: linear, animate: true, animation: fast }

    adminUser edgeAdmin@-.->|5601| subAudit
    edgeAdmin@{ curve: basis, animate: true, animation: fast }

    subControlPlane edgeConfig@-.->|5000| subAudit
    edgeConfig@{ curve: basis, animate: true, animation: fast }

    subMicroservices edgeCoreDns@==>|53| subControlPlane
    edgeCoreDns@{ curve: linear, animate: true, animation: fast }

    eventsBus edgeEventsBus@--> srvNotification
    edgeEventsBus@{ curve: linear, animate: true, animation: fast }

    srvNotification edgeEmailNotify@==> emailServer
    edgeEmailNotify@{ curve: basis, animate: true, animation: fast }

    srvNotification edgeSmsNotify@==> smsProvider
    edgeSmsNotify@{ curve: basis, animate: true, animation: fast }
  end

%% Styling & Classes
classDef redBorderNode fill:#ffffff,stroke:#e05263,stroke-width:2px,color:#000000;
classDef blueBorderNode fill:#ffffff,stroke:#4a7bb0,stroke-width:2px,color:#000000;
classDef subContainerClass fill:#ffffff,stroke:#4a7bb0,stroke-width:2px;

class containersA1,containersB1,containersA2,containersB2,containersA3 redBorderNode;
class extLoadBalancer,kubelet1,containerRuntime1,service1,kubeProxy1,kubelet2,containerRuntime2,kubeProxy2,apiServer,cloudProvider blueBorderNode;

class subWorkerNode1,subWorkerNode2,subWorkerNode3,subControlPlane subContainerClass;

%% Node Styling
classDef subContainerClass stroke:#555,rx:50,ry:100;
classDef subInnerContainerClass fill:#fdfdfd,stroke:#555,rx:25,ry:25;
classDef coreDomainContextClass fill:#dce6f8,stroke:#4a7bb0,stroke-dasharray: 4 4,stroke-width:2px;
classDef supportingDomainContextClass fill:#d3edd9,stroke:#48a05b,stroke-dasharray: 4 4,stroke-width:2px;
classDef uiClass fill:#FFFCD1,stroke:#ffe082,stroke-width:2px,color:#000000;
classDef userClass fill:#A3E2F0,stroke:#a3d5dc,stroke-width:2px,color:#000000;
classDef systemClass fill:#b2dfdb,stroke:#666666,stroke-width:2px;
classDef k8sClass fill:#DBFBFF,stroke:#4a7bb0,stroke-width:2px,color:#000000;

class subDmz,subNonDmz subContainerClass;
class subApiGateway,subMicroservices,subControlPlane,subAudit subInnerContainerClass;
class srvService1,srvService4 coreDomainContextClass;
class srvNotification,srvService3 supportingDomainContextClass;    
class mfeService1,mfeService2,mfeService3,mfeService4 uiClass;
class endUser,systemUser,adminUser userClass;
class eventsBus,databaseStorage,fileStorage,emailServer,smsProvider systemClass;
class adminKubectl,cloudProvider,controllerManager,apiServer,scheduler,cloudControllerManager,etcdStorage,ingressController,kubelet1,kubelet2,kubelet3,kubelet4,service1,containerRuntime1,containerRuntime2,containerRuntime3,containerRuntime4,kubeProxy1,kubeProxy2,kubeProxy3,kubeProxy4 k8sClass;

%% Adhoc styling
style subMainContainer fill:#fff,stroke:#666666,stroke-width:1px,rx:30px,ry:30px;
style srvReactShell fill:#ffe082,stroke:#ffb300,stroke-width:2px;
style firewall fill:#ffe7d7,stroke:#fab88c,stroke-width:8px;
style internet stroke:#666666,stroke-width:2px;
style subControlPlane fill:#fff,stroke:#4a7bb0;